import json

sponsors_data = [
    {"name": "Aannemersbedrijf Joey Smits"},
    {"name": "Aannemingsbedrijf Janssen-Groesbeek B.V."},
    {"name": "Afbouwbedrijf Looman"},
    {"name": "Agile Welzijn B.V."},
    {"name": "ALBO B.V."},
    {"name": "Alles voor de Afbouw"},
    {"name": "Automobiliteit Groesbeek"},
    {"name": "Barbershop Groesbeek"},
    {"name": "Bert Story Nijmegen"},
    {"name": "BGM Infra B.V."},
    {"name": "Bloem Direct"},
    {"name": "Burghouwt Bouwbeslag"},
    {"name": "Café Y Mas"},
    {"name": "Chef in Huis"},
    {"name": "Chem-Dry Wouters"},
    {"name": "Dakramen Groesbeek"},
    {"name": "Daktechniek Nederland"},
    {"name": "De Wolfsberg B.V."},
    {"name": "Destil"},
    {"name": "DHD Drukkerij"},
    {"name": "El Toro Restaurant & Steakhouse e.K."},
    {"name": "EP: Heinz van Benthum"},
    {"name": "Era Delicatessen"},
    {"name": "Financieringsgilde Nijmegen"},
    {"name": "FlexOnYou"},
    {"name": "Frank Lemmers Bouw"},
    {"name": "Frank van de Ven Timmerwerken"},
    {"name": "Garage De Ren"},
    {"name": "GM Tuin & Bouw"},
    {"name": "Grodak"},
    {"name": "Hagemans Verf"},
    {"name": "Handelsonderneming Coenen B.V."},
    {"name": "Hans de Echte Bakker"},
    {"name": "Hans Klein Markthandel in AGF"},
    {"name": "Hans Lamers B.V."},
    {"name": "Herberg - Restaurant 't Zwaantje"},
    {"name": "Hout & Kozijn B.V."},
    {"name": "Houzing Vloer & Interieur"},
    {"name": "HV Makelaardij"},
    {"name": "J&S Elektrotechniek"},
    {"name": "Jan Kooij 2-Wielers Groesbeek"},
    {"name": "JK Party Verhuur"},
    {"name": "Jumbo Groesbeek"},
    {"name": "K&J Timmerwerken"},
    {"name": "Kaltec Compressoren"},
    {"name": "Kerkhoff Installatiebedrijf"},
    {"name": "Konbanwa B.V."},
    {"name": "Krol Pompoenen"},
    {"name": "Langeveld Dak B.V."},
    {"name": "Leenders Vastgoedonderhoud"},
    {"name": "Lema Vloeren"},
    {"name": "MARV Websolutions"},
    {"name": "Megens Installaties"},
    {"name": "Mulders Koeltechniek"},
    {"name": "Mystery Voetbal Box"},
    {"name": "New York Pizza"},
    {"name": "Nijenkamp Dak- en Timmerwerken"},
    {"name": "Nijmeegse Cab"},
    {"name": "Niveau Glas"},
    {"name": "Numblees Corporate Finance"},
    {"name": "Onderhoudsbedrijf All Care"},
    {"name": "Optiek Groesbeek"},
    {"name": "Patron Metaal"},
    {"name": "Q-air International"},
    {"name": "Quickseal Applicatie B.V."},
    {"name": "Reclame Ellen"},
    {"name": "Rici's Garage"},
    {"name": "Rikken Reclame"},
    {"name": "Roverwood"},
    {"name": "Rozijn Parketvloeren"},
    {"name": "Sanders Tweewielers"},
    {"name": "Sann Concept Store"},
    {"name": "Schuurmans Interieur & Montage"},
    {"name": "Sieppie Kozijnen"},
    {"name": "Slagerij Tim Janssen"},
    {"name": "Slikweid B.V."},
    {"name": "STABA Maatwerk"},
    {"name": "Stadsherberg Gennep"},
    {"name": "Suselbeek Deuren"},
    {"name": "'t Soetrijck"},
    {"name": "Theunissen Timmerfabriek"},
    {"name": "Top Auto's B.V."},
    {"name": "Trofee Paleis"},
    {"name": "TSSN"},
    {"name": "Twan Janssen Schilderwerken"},
    {"name": "Univé Stad en Land B.V."},
    {"name": "Valeres Industriebouw B.V."},
    {"name": "Van Altena Groothandel"},
    {"name": "Van Kesteren Holding B.V."},
    {"name": "Van Vuuren"},
    {"name": "Van Zuijlen Auto's"},
    {"name": "Visser Keukens & Zo"},
    {"name": "Vissers Bouw & Daktechniek B.V."},
    {"name": "Voetbalschool Groesbeek"},
    {"name": "Weijerseikhout B.V."},
    {"name": "Wennekers Wonen"},
    {"name": "Wijnhoven Hout Techniek"},
    {"name": "Wouters Schoonmaakorganisatie"}
]

# Write overigesponsoren.json
with open("public/overige/overigesponsoren.json", "w", encoding="utf-8") as f:
    json.dump(sponsors_data, f, indent=2, ensure_ascii=False)

# Write updated overigesponsoren.txt
with open("public/overige/overigesponsoren.txt", "w", encoding="utf-8") as f:
    for item in sponsors_data:
        f.write(item["name"] + "\n")

print(f"Successfully generated overigesponsoren.json and updated overigesponsoren.txt with {len(sponsors_data)} sponsors.")
